version: '3'

services:
  xrayr:
    image: jat001/xrayr:latest
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    env_file:
      - .env
    volumes:
      - ./conf.d:/etc/xrayr/conf.d
      - ./node.d:/etc/xrayr/node.d
      - ./xrayr:/tmp/xrayr
    restart: always
