version: '3'

services:
  xrayr:
    build:
      context: .
      dockerfile: Dockerfile
    image: rogolezhou/xrayr:v0.9.2
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    env_file:
      - .env
    volumes:
      - ./conf.d:/etc/xrayr/conf.d
      - ./node.d:/etc/xrayr/node.d
      - ./xrayr:/tmp/xrayr
    restart: always

  acme:
    build:
      context: .  # 指定 Dockerfile 的上下文
      dockerfile: Dockerfile.cron
    image: lego-ssl:lateat
    volumes:
      - ./nginx/ssl:/etc/lego/certificates  # 挂载证书目录
    env_file:
      - cron.env
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}  # 从 cron.env 文件中读取
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}  # 从 cron.env 文件中读取
      - DOMAIN=${DOMAIN}  # 从 cron.env 文件中读取
      - WILDCARD_DOMAIN=${WILDCARD_DOMAIN} #泛域名证书参数
    entrypoint: ["/docker-cron.sh"]  # 指定入口点

  nginx:
    image: nginx:latest
    network_mode: "host"  # 使用宿主机网络
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl  # 挂载证书目录
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # 挂载 Nginx 主配置文件
      - ./nginx/conf.d:/etc/nginx/conf.d  # 挂载 Nginx 配置
    depends_on:
      - acme  # 确保 acme 服务先启动