version: '3'

services:
  xrayr:
    build:
      context: .
      dockerfile: Dockerfile
    image: rogolezhou/xrayr:v0.8.3
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    env_file:
      - .env
    volumes:
      - ./conf.d:/etc/xrayr/conf.d
      - ./node.d:/etc/xrayr/node.d
      - ./xrayr:/tmp/xrayr
    restart: always