# syntax=docker/dockerfile:1

FROM alpine:edge

RUN apk add --no-cache bash curl cronie && rm -rf /var/cache/apk/*

COPY --from=goacme/lego:latest /lego /usr/bin/lego

COPY ./docker-cron.sh /
RUN chmod +x /docker-cron.sh

ENTRYPOINT [ "/docker-cron.sh" ]
